name: Continuous Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and Publish to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_CI_TOKEN }}
        poetry publish --build
      if: startsWith(github.ref, 'refs/tags/v')
