name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with Flake8
      run: poetry run flake8 src/ --ignore=E501,F401 --exit-zero

    - name: Test with Pytest
      run: poetry run pytest

    - name: Build Package
      run: poetry build

    - name: Publish to TestPyPI on PR
      if: github.event_name == 'pull_request'
      run: |
        poetry config pypi-token.testpypi ${{ secrets.PYPI_TEST_CI_TOKEN }}
        poetry publish --repository testpypi
      env:
        POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.PYPI_TEST_CI_TOKEN }}
