# .github/workflows/release-to-pypi.yml
name: Release to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      python-version: '3.8'

  publish:
    needs: call-test-workflow
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Configure Poetry for PyPI
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_CI_TOKEN }}
      - name: Publish package to PyPI
        run: poetry publish --build
